#!/usr/bin/env python3
import csv, json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
MASTER=ROOT/'shobi-master.csv'; BEST=ROOT/'shobi-bestsellers.json'
RUNTIME=ROOT/'site-runtime-v2.json'; ENRICH=ROOT/'site-enrichment-v2.json'; DETAILS=ROOT/'site-details-v2.json'; OUT=ROOT/'index-v2.html'
def split_pipe(v): return [x.strip() for x in str(v or '').split('|') if x.strip()]
def compact(v): return re.sub(r'\s+',' ',str(v or '')).strip()
def load_best():
    try:
        d=json.loads(BEST.read_text(encoding='utf-8')); codes=d.get('codes',[]) if isinstance(d,dict) else []
        return {re.sub(r'\s+','',str(c).upper()):i+1 for i,c in enumerate(codes)}
    except Exception:return {}
def main():
    with MASTER.open(encoding='utf-8-sig',newline='') as f: rows=list(csv.DictReader(f))
    if len(rows)<500: raise SystemExit('master too small')
    ranks=load_best(); runtime=[]; enrich={}; details={}; seen=set()
    for r in rows:
        code=compact(r.get('shobi_code')); key=re.sub(r'\s+','',code.upper())
        if not code or key in seen: raise SystemExit(f'bad/duplicate code {code!r}')
        seen.add(key); name=compact(r.get('inspired_by') or r.get('shobi_name') or code); brand=compact(r.get('brand'))
        runtime.append([code,name,brand,compact(r.get('gender')).lower(),compact(r.get('status')),1 if str(r.get('new','')).strip() in ('1','true','True') else 0,ranks.get(key,0)])
        season=split_pipe(r.get('season')); notes=split_pipe(r.get('notes')); image=compact(r.get('image')); shobi=compact(r.get('shobi_url')); frag=compact(r.get('fragrantica_url'))
        enrich[key]=[season,image,notes[:6],shobi,frag]
        details[key]=[split_pipe(r.get('top_notes')),split_pipe(r.get('heart_notes')),split_pipe(r.get('base_notes')),notes,compact(r.get('description')),shobi,frag,image,compact(r.get('identity_source_type'))]
    RUNTIME.write_text(json.dumps({'v':2,'count':len(runtime),'p':runtime},ensure_ascii=False,separators=(',',':')),encoding='utf-8')
    ENRICH.write_text(json.dumps({'v':2,'e':enrich},ensure_ascii=False,separators=(',',':')),encoding='utf-8')
    DETAILS.write_text(json.dumps({'v':2,'d':details},ensure_ascii=False,separators=(',',':')),encoding='utf-8')
    css=r'''
:root{--bg:#f4f1ea;--surface:#fffdf9;--surface2:#f8f4ec;--text:#1c1b19;--muted:#77716a;--line:#ddd6cb;--accent:#b68c42;--header:#181818;--sidebar:#1d1d1d;--sideText:#eee9e1}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.4 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}button{cursor:pointer}
.app-header{position:sticky;top:0;z-index:50;background:var(--header);color:#fff;border-bottom:1px solid #2d2d2d}.header-inner{min-height:82px;padding:14px clamp(18px,2vw,34px);display:grid;grid-template-columns:270px 1fr auto;align-items:center;gap:24px}.logo{font-size:22px;font-weight:900;letter-spacing:-.04em}.subtitle{color:#aaa39a;font-size:11px;margin-top:4px}.header-center{display:flex;gap:10px;align-items:center}.head-pill,.theme-btn{border:1px solid #383838;background:#222;color:#ddd;border-radius:12px;padding:9px 12px}.head-pill.active{border-color:var(--accent);color:#f3d7a4}
.layout{width:calc(100% - clamp(24px,3vw,52px));margin:16px auto;display:grid;grid-template-columns:290px minmax(0,1fr);gap:20px;align-items:start}.sidebar{position:sticky;top:98px;height:calc(100vh - 116px);overflow:auto;background:var(--sidebar);color:var(--sideText);border:1px solid #333;border-radius:16px;padding:16px}.sidebar-title{font-weight:900;font-size:16px;margin-bottom:10px}.clear{width:100%;padding:9px;border:1px solid #3a3a3a;background:#252525;color:#eee;border-radius:10px}
.filter-group{padding-top:16px;margin-top:16px;border-top:1px solid #333}.filter-title{font-size:10px;color:#d2ac69;font-weight:900;letter-spacing:.09em;text-transform:uppercase;margin-bottom:8px}.filter-list{max-height:260px;overflow:auto}.filter-option{display:flex;gap:8px;align-items:center;padding:5px 2px;font-size:12px}.filter-option span:first-of-type{flex:1}.count{color:#aaa;font-size:10px}
.main{min-width:0}.search-wrap{position:sticky;top:94px;z-index:35;background:rgba(244,241,234,.92);backdrop-filter:blur(10px);padding:6px 0 10px}.search{width:100%;height:50px;border:1px solid var(--line);border-radius:13px;background:#fff;padding:0 15px;font-size:14px}.toolbar{display:flex;align-items:center;gap:9px;margin:10px 0 12px}.results{flex:1;color:var(--muted);font-weight:700}.sort,.page-size{height:38px;border:1px solid var(--line);background:#fff;border-radius:10px;padding:0 10px}.mobile-filter{display:none}
.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.card{position:relative;min-width:0;background:var(--surface);border:1px solid var(--line);border-radius:14px;overflow:hidden;box-shadow:0 4px 14px rgba(0,0,0,.04);content-visibility:auto;contain:layout paint;contain-intrinsic-size:360px 230px}.card-image-wrap{height:155px;background:var(--surface2);display:grid;place-items:center;overflow:hidden}.card-image{width:100%;height:100%;object-fit:contain;padding:10px}.image-placeholder{font-size:11px;color:#aaa}.card-body{padding:12px}.perfume-name{font-weight:900;font-size:13px;line-height:1.25;min-height:33px}.brand{font-size:10px;font-weight:800;color:#9b7737;margin-top:4px;text-transform:uppercase}.code{font:9px ui-monospace,monospace;color:#999;margin-top:5px}
.badges,.notes{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.badge,.note-chip{font-size:8px;border:1px solid var(--line);border-radius:999px;padding:4px 6px;background:#faf7f0}.new-badge{background:#1c1c1c;color:white;border-color:#1c1c1c}.rank{color:#9b7737}.card-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:10px}.card-actions button,.card-actions a{min-height:29px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--text);text-decoration:none;display:grid;place-items:center;font-size:9px;font-weight:800}.card-actions .details{grid-column:1/-1;background:#181818;color:#fff;border-color:#181818}.fav{position:absolute;right:8px;top:8px;z-index:2;width:31px;height:31px;border-radius:50%;border:1px solid #ddd;background:#fff}.fav.active{background:#181818;color:#fff}.owned.active,.compare.active{border-color:var(--accent);color:#936d2e;background:#fff9ed}
.pagination{display:flex;gap:6px;justify-content:center;align-items:center;padding:18px 0 28px}.pagination button{border:1px solid var(--line);background:#fff;border-radius:9px;padding:7px 10px}.pagination button.active{background:#181818;color:#fff}.status{font-size:11px;color:var(--muted);margin:4px 0 8px}.skeleton{min-height:320px;background:linear-gradient(90deg,#eee 25%,#f7f7f7 38%,#eee 63%);background-size:400% 100%;animation:sh 1.3s infinite;border-radius:14px}@keyframes sh{0%{background-position:100% 0}100%{background-position:-100% 0}}
.overlay{position:fixed;inset:0;z-index:100;background:rgba(0,0,0,.56);display:grid;place-items:center;padding:20px}.overlay[hidden]{display:none}.modal{width:min(900px,96vw);max-height:90vh;overflow:auto;background:var(--surface);border-radius:18px;padding:20px;position:relative}.close{position:sticky;float:right;top:0;width:38px;height:38px;border:1px solid var(--line);background:#fff;border-radius:10px}.modal-grid{display:grid;grid-template-columns:240px 1fr;gap:22px}.modal-image{width:100%;height:260px;object-fit:contain;background:var(--surface2);border-radius:12px}.pyramid{display:grid;gap:10px;margin-top:14px}.pyr-row{padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--surface2)}.pyr-title{font-size:9px;color:#977339;font-weight:900;text-transform:uppercase;margin-bottom:5px}.modal-links{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.modal-links a{padding:8px 10px;border-radius:9px;background:#181818;color:#fff;text-decoration:none;font-size:11px}.compare-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.empty{grid-column:1/-1;padding:60px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}
[data-theme="dark"]{--bg:#111;--surface:#1d1d1d;--surface2:#252525;--text:#f1eee8;--muted:#aaa39a;--line:#383838}[data-theme="dark"] .search,[data-theme="dark"] .sort,[data-theme="dark"] .page-size,[data-theme="dark"] .pagination button,[data-theme="dark"] .card-actions button,[data-theme="dark"] .fav,[data-theme="dark"] .close{background:#202020;color:#eee}
@media(max-width:1500px){.grid{grid-template-columns:repeat(5,1fr)}}@media(max-width:1250px){.grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:980px){.header-inner{grid-template-columns:1fr auto}.header-center{display:none}.layout{grid-template-columns:1fr}.sidebar{display:none;position:fixed;top:0;left:0;z-index:80;width:min(340px,90vw);height:100vh;border-radius:0}.sidebar.open{display:block}.mobile-filter{display:inline-block}.grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:680px){.grid{grid-template-columns:repeat(2,1fr)}.modal-grid{grid-template-columns:1fr}.modal-image{height:210px}.compare-grid{grid-template-columns:1fr}}@media(max-width:420px){.grid{grid-template-columns:1fr}}
'''
    html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shobi Perfume Database</title><link rel="preload" href="./site-runtime-v2.json" as="fetch"><style>'''+css+'''</style></head><body>
<header class="app-header"><div class="header-inner"><div><div class="logo">Shobi Perfume Database</div><div class="subtitle">Official Shobi catalogue · canonical master database</div></div><div class="header-center"><button id="collectionToggle" class="head-pill">◇ Collection <span id="ownedCount">0</span></button><button id="favoriteToggle" class="head-pill">♡ Favorites <span id="favCount">0</span></button><button id="compareToggle" class="head-pill">Compare <span id="compareCount">0/3</span></button></div><button id="themeToggle" class="theme-btn">◐ Theme</button></div></header>
<div class="layout"><aside id="sidebar" class="sidebar"><div class="sidebar-title">FILTERS</div><button id="clearFilters" class="clear">Clear filters</button><div id="filters"></div></aside>
<main class="main"><div class="search-wrap"><input id="search" class="search" type="search" placeholder="🔍 Search perfume, brand, code..." autocomplete="off"></div><div id="status" class="status">Loading fragrances…</div><div class="toolbar"><button id="mobileFilter" class="mobile-filter">Filters</button><div id="results" class="results">0 fragrances</div><select id="sort" class="sort"><option value="bestsellers">Best Sellers</option><option value="az">Name A → Z</option><option value="za">Name Z → A</option><option value="brandaz">Brand A → Z</option><option value="brandza">Brand Z → A</option></select><select id="pageSize" class="page-size"><option>24</option><option selected>48</option><option>96</option></select></div><section id="grid" class="grid"></section><nav id="pagination" class="pagination"></nav></main></div>
<div id="detailOverlay" class="overlay" hidden><div class="modal"><button class="close" data-close="detail">✕</button><div id="detailBody"></div></div></div><div id="compareOverlay" class="overlay" hidden><div class="modal"><button class="close" data-close="compare">✕</button><h2>Compare</h2><div id="compareBody" class="compare-grid"></div></div></div>
<script>
"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));const norm=v=>String(v||"").trim().toLowerCase(),ck=v=>String(v||"").toUpperCase().replace(/\s+/g,"");const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const collator=new Intl.Collator("en",{sensitivity:"base"});
let perfumes=[],filtered=[],enrich=null,details=null,page=1,pageSize=48,query="",sortMode="bestsellers",collectionOnly=false,favoritesOnly=false;let selected={brand:new Set(),gender:new Set(),season:new Set(),note:new Set()};const favorites=new Set(JSON.parse(localStorage.getItem("shobiFavoritesV2")||"[]")),owned=new Set(JSON.parse(localStorage.getItem("shobiOwnedV2")||"[]")),compare=new Set(),byCode=new Map();
function saveSet(k,s){localStorage.setItem(k,JSON.stringify(Array.from(s)))}function skeleton(){$("#grid").innerHTML=Array.from({length:18},()=>'<div class="skeleton"></div>').join("")}function hasFilters(){return query||collectionOnly||favoritesOnly||selected.brand.size||selected.gender.size||selected.season.size||selected.note.size}function extra(p){return enrich&&enrich[ck(p.code)]||[[],"",[],"",""]}
function matches(p){if(query&&!norm([p.name,p.brand,p.code].join(" ")).includes(norm(query)))return false;if(collectionOnly&&!owned.has(ck(p.code)))return false;if(favoritesOnly&&!favorites.has(ck(p.code)))return false;if(selected.brand.size&&!selected.brand.has(p.brand))return false;if(selected.gender.size&&!selected.gender.has(p.gender))return false;const x=extra(p),se=x[0]||[],no=x[2]||[];if(selected.season.size&&![...selected.season].every(v=>se.includes(v)))return false;if(selected.note.size&&![...selected.note].every(v=>no.includes(v)))return false;return true}
function apply(){filtered=hasFilters()?perfumes.filter(matches):perfumes.slice();if(sortMode==="bestsellers")filtered.sort((a,b)=>(a.rank||1e9)-(b.rank||1e9)||a.id-b.id);else if(sortMode==="az")filtered.sort((a,b)=>collator.compare(a.name,b.name));else if(sortMode==="za")filtered.sort((a,b)=>collator.compare(b.name,a.name));else if(sortMode==="brandaz")filtered.sort((a,b)=>collator.compare(a.brand,b.brand)||collator.compare(a.name,b.name));else filtered.sort((a,b)=>collator.compare(b.brand,a.brand)||collator.compare(b.name,a.name));const n=Math.max(1,Math.ceil(filtered.length/pageSize));if(page>n)page=n;render();counts()}
function card(p){const x=extra(p),se=x[0]||[],img=x[1]||"",notes=x[2]||[],sh=x[3]||"",key=ck(p.code);return `<article class="card" data-code="${esc(key)}"><button class="fav ${favorites.has(key)?"active":""}" data-action="fav">${favorites.has(key)?"♥":"♡"}</button><div class="card-image-wrap">${img?`<img class="card-image" src="${esc(img)}" alt="" loading="lazy" decoding="async">`:'<span class="image-placeholder">Image coming soon</span>'}</div><div class="card-body"><div class="perfume-name">${esc(p.name.toUpperCase())}</div><div class="brand">${esc(p.brand)}</div><div class="code">${esc(p.code)}</div><div class="badges">${p.gender?`<button class="badge" data-action="gender">${esc(p.gender)}</button>`:""}${se.map(v=>`<button class="badge" data-action="season" data-value="${esc(v)}">${esc(v)}</button>`).join("")}${p.isNew?'<span class="badge new-badge">NEW</span>':""}${p.rank?`<span class="badge rank">#${p.rank}</span>`:""}</div><div class="notes">${notes.slice(0,4).map(v=>`<button class="note-chip" data-action="note" data-value="${esc(v)}">${esc(v)}</button>`).join("")}</div><div class="card-actions"><button class="owned ${owned.has(key)?"active":""}" data-action="owned">${owned.has(key)?"Owned":"Collection"}</button><button class="compare ${compare.has(key)?"active":""}" data-action="compare">Compare</button>${sh?`<a href="${esc(sh)}" target="_blank" rel="noopener" data-action="link">SHOP ON SHOBI</a>`:""}<button class="details" data-action="details">More detail</button></div></div></article>`}
function render(){const s=(page-1)*pageSize,a=filtered.slice(s,s+pageSize);$("#grid").innerHTML=a.length?a.map(card).join(""):'<div class="empty">No fragrances found.</div>';pagination()}
function pagination(){const n=Math.max(1,Math.ceil(filtered.length/pageSize)),el=$("#pagination");if(n<=1){el.innerHTML="";return}let a=[],f=Math.max(1,page-2),t=Math.min(n,page+2);if(page>1)a.push(`<button data-page="${page-1}">‹</button>`);for(let i=f;i<=t;i++)a.push(`<button class="${i===page?"active":""}" data-page="${i}">${i}</button>`);if(page<n)a.push(`<button data-page="${page+1}">›</button>`);el.innerHTML=a.join("")}
function counts(){$("#results").textContent=`${filtered.length.toLocaleString()} fragrances`;$("#favCount").textContent=favorites.size;$("#ownedCount").textContent=owned.size;$("#compareCount").textContent=`${compare.size}/3`;$("#favoriteToggle").classList.toggle("active",favoritesOnly);$("#collectionToggle").classList.toggle("active",collectionOnly)}
function fg(title,key,vals){const m=new Map();perfumes.forEach(p=>{let a=key==="brand"?[p.brand]:key==="gender"?[p.gender]:key==="season"?(extra(p)[0]||[]):(extra(p)[2]||[]);a.filter(Boolean).forEach(v=>m.set(v,(m.get(v)||0)+1))});const arr=Array.from(new Set(vals||Array.from(m.keys()))).filter(Boolean).sort(collator.compare);return `<div class="filter-group"><div class="filter-title">${esc(title)}</div><div class="filter-list">${arr.map(v=>`<label class="filter-option"><input type="checkbox" data-filter="${key}" value="${esc(v)}" ${selected[key].has(v)?"checked":""}><span>${esc(v)}</span><span class="count">${m.get(v)||0}</span></label>`).join("")}</div></div>`}
function buildFilters(){const b=perfumes.map(p=>p.brand);$("#filters").innerHTML=fg("Gender","gender",["men","women","unisex"])+fg("Season","season")+fg("Brand","brand",b)+(enrich?fg("Notes","note"):"")}
async function loadEnrichment(){if(enrich)return;try{const r=await fetch("./site-enrichment-v2.json",{cache:"force-cache"});if(!r.ok)throw Error(r.status);enrich=(await r.json()).e||{};buildFilters();render()}catch(e){console.warn("enrichment load failed",e)}}async function ensureDetails(){if(details)return details;const r=await fetch("./site-details-v2.json",{cache:"force-cache"});if(!r.ok)throw Error(r.status);details=(await r.json()).d||{};return details}
function pyr(t,a){return a&&a.length?`<div class="pyr-row"><div class="pyr-title">${t}</div><div>${a.map(esc).join(" · ")}</div></div>`:""}async function openDetail(code){const p=byCode.get(ck(code));if(!p)return;$("#detailOverlay").hidden=false;$("#detailBody").innerHTML="<p>Loading details…</p>";try{const x=(await ensureDetails())[ck(code)]||[[],[],[],[],"","","","", ""];$("#detailBody").innerHTML=`<div class="modal-grid"><div>${x[7]?`<img class="modal-image" src="${esc(x[7])}" alt="">`:""}</div><div><h2>${esc(p.name)}</h2><div class="brand">${esc(p.brand)}</div><div class="code">${esc(p.code)}</div>${x[4]?`<p>${esc(x[4])}</p>`:""}<div class="pyramid">${pyr("Top Notes",x[0])}${pyr("Heart Notes",x[1])}${pyr("Base Notes",x[2])}${(!x[0].length&&!x[1].length&&!x[2].length)?pyr("Notes",x[3]):""}</div><div class="modal-links">${x[5]?`<a href="${esc(x[5])}" target="_blank" rel="noopener">SHOP ON SHOBI</a>`:""}${x[6]?`<a href="${esc(x[6])}" target="_blank" rel="noopener">Fragrantica ↗</a>`:""}</div>${x[8]?`<p class="status">Identity source: ${esc(x[8])}</p>`:""}</div></div>`}catch(e){$("#detailBody").innerHTML="<p>Details unavailable.</p>"}}
async function openCompare(){if(compare.size<2)return;$("#compareOverlay").hidden=false;$("#compareBody").innerHTML="<p>Loading…</p>";const d=await ensureDetails();$("#compareBody").innerHTML=Array.from(compare).map(k=>{const p=byCode.get(k),x=d[k]||[[],[],[],[],"","","",""];return `<div><h3>${esc(p.name)}</h3><div class="brand">${esc(p.brand)}</div>${x[7]?`<img class="modal-image" src="${esc(x[7])}" alt="">`:""}${pyr("Top",x[0])}${pyr("Heart",x[1])}${pyr("Base",x[2])}</div>`}).join("")}
function toggle(s,k,max=Infinity){if(s.has(k))s.delete(k);else if(s.size<max)s.add(k)}
$("#grid").addEventListener("click",e=>{const c=e.target.closest(".card");if(!c)return;const k=c.dataset.code,a=e.target.closest("[data-action]")?.dataset.action;if(a==="link")return;if(a==="fav"){toggle(favorites,k);saveSet("shobiFavoritesV2",favorites);render();counts()}else if(a==="owned"){toggle(owned,k);saveSet("shobiOwnedV2",owned);render();counts()}else if(a==="compare"){toggle(compare,k,3);render();counts()}else if(a==="gender"){selected.gender.add(byCode.get(k).gender);page=1;buildFilters();apply()}else if(a==="season"||a==="note"){selected[a].add(e.target.closest("[data-value]").dataset.value);page=1;buildFilters();apply()}else if(a==="details"||!a)openDetail(k)});
$("#filters").addEventListener("change",e=>{const k=e.target.dataset.filter;if(!k)return;const v=e.target.value;e.target.checked?selected[k].add(v):selected[k].delete(v);page=1;apply()});$("#pagination").addEventListener("click",e=>{const p=Number(e.target.dataset.page);if(p){page=p;render();window.scrollTo({top:0,behavior:"smooth"})}});$("#search").addEventListener("input",e=>{query=e.target.value;page=1;apply()});$("#sort").addEventListener("change",e=>{sortMode=e.target.value;page=1;apply()});$("#pageSize").addEventListener("change",e=>{pageSize=Number(e.target.value)||48;page=1;render()});
$("#clearFilters").addEventListener("click",()=>{query="";$("#search").value="";Object.values(selected).forEach(s=>s.clear());collectionOnly=favoritesOnly=false;page=1;buildFilters();apply()});$("#favoriteToggle").addEventListener("click",()=>{favoritesOnly=!favoritesOnly;collectionOnly=false;page=1;apply()});$("#collectionToggle").addEventListener("click",()=>{collectionOnly=!collectionOnly;favoritesOnly=false;page=1;apply()});$("#compareToggle").addEventListener("click",openCompare);$("#themeToggle").addEventListener("click",()=>{const d=document.documentElement.dataset.theme==="dark";document.documentElement.dataset.theme=d?"light":"dark";localStorage.setItem("shobiThemeV2",d?"light":"dark")});$("#mobileFilter").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));$$("[data-close]").forEach(b=>b.addEventListener("click",()=>$("#"+b.dataset.close+"Overlay").hidden=true));$$(".overlay").forEach(o=>o.addEventListener("click",e=>{if(e.target===o)o.hidden=true}));document.documentElement.dataset.theme=localStorage.getItem("shobiThemeV2")||"light";
async function boot(){skeleton();const t=performance.now();try{const r=await fetch("./site-runtime-v2.json",{cache:"force-cache"});if(!r.ok)throw Error(r.status);const d=await r.json();perfumes=(d.p||[]).map((x,i)=>({id:i,code:x[0],name:x[1],brand:x[2],gender:x[3],status:x[4],isNew:!!x[5],rank:x[6]||0}));perfumes.forEach(p=>byCode.set(ck(p.code),p));filtered=perfumes.slice();$("#status").textContent=`${perfumes.length.toLocaleString()} perfumes loaded in ${Math.round(performance.now()-t)} ms`;apply();requestAnimationFrame(()=>{buildFilters();const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,500));idle(loadEnrichment,{timeout:1500})})}catch(e){$("#status").textContent="Catalogue unavailable";$("#grid").innerHTML='<div class="empty">Unable to load catalogue.</div>';console.error(e)}}boot();
</script></body></html>'''
    OUT.write_text(html,encoding='utf-8')
    print('V2_ROWS',len(runtime));print('RUNTIME_BYTES',RUNTIME.stat().st_size);print('ENRICH_BYTES',ENRICH.stat().st_size);print('DETAILS_BYTES',DETAILS.stat().st_size);print('INDEX_V2_BYTES',OUT.stat().st_size)
if __name__=='__main__': main()
